apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-ml
  name: car-repair-predication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-ml
  template:
    metadata:
      labels:
        app: ai-ml
    spec:
      containers:
        - image: quay.io/praveenrachamreddy/ci-pipeline:latest
          imagePullPolicy: Always
          name: ai-ml
          ports:
            - containerPort: 8080
              protocol: TCP
